# Generated by Django 3.2.4 on 2021-07-02 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfo',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='funFact',
            field=models.TextField(default='Enter your fun fact here'),
        ),
    ]
